# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signalwin.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignalWin(object):
    def setupUi(self, SignalWin):
        SignalWin.setObjectName("SignalWin")
        SignalWin.setEnabled(True)
        SignalWin.resize(1719, 877)
        self.signalTable = QtWidgets.QTableWidget(SignalWin)
        self.signalTable.setGeometry(QtCore.QRect(30, 80, 941, 151))
        self.signalTable.setMinimumSize(QtCore.QSize(941, 0))
        self.signalTable.setObjectName("signalTable")
        self.signalTable.setColumnCount(8)
        self.signalTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.signalTable.setHorizontalHeaderItem(7, item)
        self.label = QtWidgets.QLabel(SignalWin)
        self.label.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.label.setObjectName("label")
        self.signalAddBT = QtWidgets.QPushButton(SignalWin)
        self.signalAddBT.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.signalAddBT.setObjectName("signalAddBT")
        self.signalDeleteBT = QtWidgets.QPushButton(SignalWin)
        self.signalDeleteBT.setGeometry(QtCore.QRect(120, 40, 75, 23))
        self.signalDeleteBT.setObjectName("signalDeleteBT")
        self.saveSignalBT = QtWidgets.QPushButton(SignalWin)
        self.saveSignalBT.setGeometry(QtCore.QRect(230, 40, 75, 23))
        self.saveSignalBT.setObjectName("saveSignalBT")
        self.objectTable = QtWidgets.QTableWidget(SignalWin)
        self.objectTable.setGeometry(QtCore.QRect(10, 560, 1721, 281))
        self.objectTable.setObjectName("objectTable")
        self.objectTable.setColumnCount(17)
        self.objectTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.objectTable.setHorizontalHeaderItem(16, item)
        self.manualCBB = QtWidgets.QComboBox(SignalWin)
        self.manualCBB.setGeometry(QtCore.QRect(100, 340, 81, 22))
        self.manualCBB.setObjectName("manualCBB")
        self.manualCBB.addItem("")
        self.manualCBB.addItem("")
        self.label_2 = QtWidgets.QLabel(SignalWin)
        self.label_2.setGeometry(QtCore.QRect(10, 342, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(SignalWin)
        self.label_4.setGeometry(QtCore.QRect(10, 380, 21, 20))
        self.label_4.setObjectName("label_4")
        self.srLE = QtWidgets.QLineEdit(SignalWin)
        self.srLE.setGeometry(QtCore.QRect(60, 380, 101, 20))
        self.srLE.setObjectName("srLE")
        self.stLE = QtWidgets.QLineEdit(SignalWin)
        self.stLE.setGeometry(QtCore.QRect(200, 380, 101, 20))
        self.stLE.setText("")
        self.stLE.setObjectName("stLE")
        self.label_5 = QtWidgets.QLabel(SignalWin)
        self.label_5.setGeometry(QtCore.QRect(170, 380, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(SignalWin)
        self.label_6.setGeometry(QtCore.QRect(500, 380, 31, 20))
        self.label_6.setObjectName("label_6")
        self.typeLE = QtWidgets.QLineEdit(SignalWin)
        self.typeLE.setGeometry(QtCore.QRect(540, 380, 101, 20))
        self.typeLE.setText("")
        self.typeLE.setObjectName("typeLE")
        self.label_7 = QtWidgets.QLabel(SignalWin)
        self.label_7.setGeometry(QtCore.QRect(660, 380, 31, 20))
        self.label_7.setObjectName("label_7")
        self.nameLE = QtWidgets.QLineEdit(SignalWin)
        self.nameLE.setGeometry(QtCore.QRect(700, 380, 121, 20))
        self.nameLE.setText("")
        self.nameLE.setObjectName("nameLE")
        self.label_8 = QtWidgets.QLabel(SignalWin)
        self.label_8.setGeometry(QtCore.QRect(830, 380, 21, 20))
        self.label_8.setObjectName("label_8")
        self.idLE = QtWidgets.QLineEdit(SignalWin)
        self.idLE.setGeometry(QtCore.QRect(860, 380, 101, 20))
        self.idLE.setText("")
        self.idLE.setObjectName("idLE")
        self.sLE = QtWidgets.QLineEdit(SignalWin)
        self.sLE.setGeometry(QtCore.QRect(1000, 380, 161, 20))
        self.sLE.setText("")
        self.sLE.setObjectName("sLE")
        self.label_9 = QtWidgets.QLabel(SignalWin)
        self.label_9.setGeometry(QtCore.QRect(980, 380, 21, 20))
        self.label_9.setObjectName("label_9")
        self.tLE = QtWidgets.QLineEdit(SignalWin)
        self.tLE.setGeometry(QtCore.QRect(1200, 380, 161, 20))
        self.tLE.setText("")
        self.tLE.setObjectName("tLE")
        self.label_10 = QtWidgets.QLabel(SignalWin)
        self.label_10.setGeometry(QtCore.QRect(1180, 380, 16, 20))
        self.label_10.setObjectName("label_10")
        self.zOffsetLE = QtWidgets.QLineEdit(SignalWin)
        self.zOffsetLE.setGeometry(QtCore.QRect(60, 410, 151, 20))
        self.zOffsetLE.setObjectName("zOffsetLE")
        self.label_11 = QtWidgets.QLabel(SignalWin)
        self.label_11.setGeometry(QtCore.QRect(10, 410, 51, 20))
        self.label_11.setObjectName("label_11")
        self.validLengthLE = QtWidgets.QLineEdit(SignalWin)
        self.validLengthLE.setGeometry(QtCore.QRect(310, 410, 161, 20))
        self.validLengthLE.setObjectName("validLengthLE")
        self.label_12 = QtWidgets.QLabel(SignalWin)
        self.label_12.setGeometry(QtCore.QRect(230, 410, 71, 20))
        self.label_12.setObjectName("label_12")
        self.orientationLE = QtWidgets.QLineEdit(SignalWin)
        self.orientationLE.setGeometry(QtCore.QRect(570, 410, 101, 20))
        self.orientationLE.setObjectName("orientationLE")
        self.label_13 = QtWidgets.QLabel(SignalWin)
        self.label_13.setGeometry(QtCore.QRect(490, 410, 71, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(SignalWin)
        self.label_14.setGeometry(QtCore.QRect(690, 410, 41, 20))
        self.label_14.setObjectName("label_14")
        self.lengthLE = QtWidgets.QLineEdit(SignalWin)
        self.lengthLE.setGeometry(QtCore.QRect(740, 410, 151, 20))
        self.lengthLE.setObjectName("lengthLE")
        self.label_15 = QtWidgets.QLabel(SignalWin)
        self.label_15.setGeometry(QtCore.QRect(910, 410, 41, 20))
        self.label_15.setObjectName("label_15")
        self.widthLE = QtWidgets.QLineEdit(SignalWin)
        self.widthLE.setGeometry(QtCore.QRect(960, 410, 161, 20))
        self.widthLE.setObjectName("widthLE")
        self.heightLE = QtWidgets.QLineEdit(SignalWin)
        self.heightLE.setGeometry(QtCore.QRect(1200, 410, 161, 20))
        self.heightLE.setObjectName("heightLE")
        self.label_16 = QtWidgets.QLabel(SignalWin)
        self.label_16.setGeometry(QtCore.QRect(1150, 410, 41, 20))
        self.label_16.setObjectName("label_16")
        self.hdgLE = QtWidgets.QLineEdit(SignalWin)
        self.hdgLE.setGeometry(QtCore.QRect(60, 440, 151, 20))
        self.hdgLE.setObjectName("hdgLE")
        self.label_17 = QtWidgets.QLabel(SignalWin)
        self.label_17.setGeometry(QtCore.QRect(10, 440, 41, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(SignalWin)
        self.label_18.setGeometry(QtCore.QRect(260, 440, 41, 20))
        self.label_18.setObjectName("label_18")
        self.pitchLE = QtWidgets.QLineEdit(SignalWin)
        self.pitchLE.setGeometry(QtCore.QRect(310, 440, 161, 20))
        self.pitchLE.setObjectName("pitchLE")
        self.rollLE = QtWidgets.QLineEdit(SignalWin)
        self.rollLE.setGeometry(QtCore.QRect(570, 440, 151, 20))
        self.rollLE.setObjectName("rollLE")
        self.label_19 = QtWidgets.QLabel(SignalWin)
        self.label_19.setGeometry(QtCore.QRect(520, 440, 41, 20))
        self.label_19.setObjectName("label_19")
        self.objectAddBT = QtWidgets.QPushButton(SignalWin)
        self.objectAddBT.setGeometry(QtCore.QRect(10, 520, 75, 23))
        self.objectAddBT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.objectAddBT.setObjectName("objectAddBT")
        self.objectDeleteBT = QtWidgets.QPushButton(SignalWin)
        self.objectDeleteBT.setGeometry(QtCore.QRect(100, 520, 75, 23))
        self.objectDeleteBT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.objectDeleteBT.setObjectName("objectDeleteBT")
        self.saveObjectBT = QtWidgets.QPushButton(SignalWin)
        self.saveObjectBT.setGeometry(QtCore.QRect(220, 520, 75, 23))
        self.saveObjectBT.setObjectName("saveObjectBT")
        self.label_20 = QtWidgets.QLabel(SignalWin)
        self.label_20.setGeometry(QtCore.QRect(320, 380, 21, 20))
        self.label_20.setObjectName("label_20")
        self.shLE = QtWidgets.QLineEdit(SignalWin)
        self.shLE.setGeometry(QtCore.QRect(350, 380, 101, 20))
        self.shLE.setText("")
        self.shLE.setObjectName("shLE")

        self.retranslateUi(SignalWin)
        QtCore.QMetaObject.connectSlotsByName(SignalWin)

    def retranslateUi(self, SignalWin):
        _translate = QtCore.QCoreApplication.translate
        SignalWin.setWindowTitle(_translate("SignalWin", "信号灯编辑"))
        item = self.signalTable.horizontalHeaderItem(0)
        item.setText(_translate("SignalWin", "id"))
        item = self.signalTable.horizontalHeaderItem(1)
        item.setText(_translate("SignalWin", "type"))
        item = self.signalTable.horizontalHeaderItem(2)
        item.setText(_translate("SignalWin", "subtype"))
        item = self.signalTable.horizontalHeaderItem(3)
        item.setText(_translate("SignalWin", "roadid"))
        item = self.signalTable.horizontalHeaderItem(4)
        item.setText(_translate("SignalWin", "s"))
        item = self.signalTable.horizontalHeaderItem(5)
        item.setText(_translate("SignalWin", "t"))
        item = self.signalTable.horizontalHeaderItem(6)
        item.setText(_translate("SignalWin", "h"))
        item = self.signalTable.horizontalHeaderItem(7)
        item.setText(_translate("SignalWin", "reference"))
        self.label.setText(_translate("SignalWin", "信号灯编辑："))
        self.signalAddBT.setText(_translate("SignalWin", "添加行"))
        self.signalDeleteBT.setText(_translate("SignalWin", "删除行"))
        self.saveSignalBT.setText(_translate("SignalWin", "保存"))
        item = self.objectTable.horizontalHeaderItem(0)
        item.setText(_translate("SignalWin", "sr"))
        item = self.objectTable.horizontalHeaderItem(1)
        item.setText(_translate("SignalWin", "st"))
        item = self.objectTable.horizontalHeaderItem(2)
        item.setText(_translate("SignalWin", "sh"))
        item = self.objectTable.horizontalHeaderItem(3)
        item.setText(_translate("SignalWin", "type"))
        item = self.objectTable.horizontalHeaderItem(4)
        item.setText(_translate("SignalWin", "name"))
        item = self.objectTable.horizontalHeaderItem(5)
        item.setText(_translate("SignalWin", "id"))
        item = self.objectTable.horizontalHeaderItem(6)
        item.setText(_translate("SignalWin", "s"))
        item = self.objectTable.horizontalHeaderItem(7)
        item.setText(_translate("SignalWin", "t"))
        item = self.objectTable.horizontalHeaderItem(8)
        item.setText(_translate("SignalWin", "zOffset"))
        item = self.objectTable.horizontalHeaderItem(9)
        item.setText(_translate("SignalWin", "validLength"))
        item = self.objectTable.horizontalHeaderItem(10)
        item.setText(_translate("SignalWin", "orientation"))
        item = self.objectTable.horizontalHeaderItem(11)
        item.setText(_translate("SignalWin", "length"))
        item = self.objectTable.horizontalHeaderItem(12)
        item.setText(_translate("SignalWin", "width"))
        item = self.objectTable.horizontalHeaderItem(13)
        item.setText(_translate("SignalWin", "height"))
        item = self.objectTable.horizontalHeaderItem(14)
        item.setText(_translate("SignalWin", "hdg"))
        item = self.objectTable.horizontalHeaderItem(15)
        item.setText(_translate("SignalWin", "pitch"))
        item = self.objectTable.horizontalHeaderItem(16)
        item.setText(_translate("SignalWin", "roll"))
        self.manualCBB.setItemText(0, _translate("SignalWin", "否"))
        self.manualCBB.setItemText(1, _translate("SignalWin", "是"))
        self.label_2.setText(_translate("SignalWin", "是否手工处理："))
        self.label_4.setText(_translate("SignalWin", "sr："))
        self.label_5.setText(_translate("SignalWin", "st："))
        self.label_6.setText(_translate("SignalWin", "type："))
        self.label_7.setText(_translate("SignalWin", "name："))
        self.label_8.setText(_translate("SignalWin", "id："))
        self.label_9.setText(_translate("SignalWin", "s："))
        self.label_10.setText(_translate("SignalWin", "t："))
        self.zOffsetLE.setText(_translate("SignalWin", "2.0000000000000000e-02"))
        self.label_11.setText(_translate("SignalWin", "zOffset："))
        self.validLengthLE.setText(_translate("SignalWin", "0.0000000000000000e+00"))
        self.label_12.setText(_translate("SignalWin", "validLength："))
        self.orientationLE.setText(_translate("SignalWin", "none"))
        self.label_13.setText(_translate("SignalWin", "orientation："))
        self.label_14.setText(_translate("SignalWin", "length："))
        self.lengthLE.setText(_translate("SignalWin", "1.0000000000000000e+00"))
        self.label_15.setText(_translate("SignalWin", "width："))
        self.widthLE.setText(_translate("SignalWin", "1.0000000000000000e+00"))
        self.heightLE.setText(_translate("SignalWin", "0.0000000000000000e+00"))
        self.label_16.setText(_translate("SignalWin", "height："))
        self.hdgLE.setText(_translate("SignalWin", "0.0000000000000000e+00"))
        self.label_17.setText(_translate("SignalWin", "hdg："))
        self.label_18.setText(_translate("SignalWin", "pitch："))
        self.pitchLE.setText(_translate("SignalWin", "0.0000000000000000e+00"))
        self.rollLE.setText(_translate("SignalWin", "0.0000000000000000e+00"))
        self.label_19.setText(_translate("SignalWin", "roll："))
        self.objectAddBT.setText(_translate("SignalWin", "添加行"))
        self.objectDeleteBT.setText(_translate("SignalWin", "删除行"))
        self.saveObjectBT.setText(_translate("SignalWin", "保存"))
        self.label_20.setText(_translate("SignalWin", "sh："))

